### PR TITLE
Added timestamps for time of creation and last modified. 

### PR DESCRIPTION
**Pull request by fernandalavalle**
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/isitketo_webapp/69)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CI1H1x8QYQc5G0CI:-L62CI1H1x8QYQc5G0CJ:bsilpbt) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/README.md#L8)):*
> ```Markdown
> # Dev Installation
> 
> To run IsItKeto:
> ```

I know this is just to get Travis to re-run, but I don't want to add noise to the changelist for Travis. Can we take this out?

Another way to force a Travis re-run is to just close the PR and reopen it.

---

*[app/admin.py, line 44 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CMW0sYUCzBwNGTg0:-L62CMW0sYUCzBwNGTg1:bdag7of) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/app/admin.py#L44)):*
> ```Python
>     f = food.find_by_name(food_name)
>     f = _update_food_from_form(f)
>     f = food.update(food_name, f)
> ```

I was confused that we're using the term "update" to refer to two separate functions that do very different things.

Can we keep `_make_food_from_form` and have `food.update` handle putting the new fields into the existing Food entry? We should add unit tests for that as well.

---

*[app/templates/food_form.html, line 61 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CR4ytun3lcLS5TyS:-L62CR4ytun3lcLS5TyT:b-lwb8e2) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/app/templates/food_form.html#L61)):*
> ```HTML
> </div>
> 
> {% include 'footer.html' %}
> ```

This looks like a stray edit. Can we remove this file from the PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/admin.py, line 44 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CMW0sYUCzBwNGTg0:-L63IE_YGgkoTWcy-Bnm:b-ziynw) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/app/admin.py#L44)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I was confused that we're using the term "update" to refer to two separate functions that do very different things.

Can we keep `_make_food_from_form` and have `food.update` handle putting the new fields into the existing Food entry? We should add unit tests for that as well.
</blockquote></details>

Do you think it would be clearer to call it something like "_define_food_from_form"? 

To me it makes more sense for add and edit to be almost identical except with update requesting the existing object. Also moving anything related to the form to food.py feels weird, and passing a dictionary or something of the new properties to food.update feels redundant when the _update_food_from_form basically does that. 

Unit tests that ensure that the right values get assigned to food objects? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69)*

**Comment by mtlynch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/admin.py, line 44 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CMW0sYUCzBwNGTg0:-L63ULMlaZAMGh44L-Le:br15f29) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/app/admin.py#L44)):*
Yeah,  I agree on making `api_add_food` and `api_edit_food` almost if not entirely identical.

I'd like it to be like:

```python
def api_add_food():
    f = _make_food_from_form()
    food.put(f)
    return flask.redirect('/%s' % f.key.string_id())
...

def api_edit_food(food_name):
    f = food.update(food_name, _make_food_from_form())
    return flask.redirect('/%s' % f.key.string_id())
```

>Unit tests that ensure that the right values get assigned to food objects?

Yeah, I'm mainly interested in verifying scenarios like:

1. Food already exists, we call `update` with the exact same Food -> Verify that everything stays the same except the updated timestamp.
1. Food already exists,we call `update` with some fields changed -> Verify that those fields changed + new update timestamp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/admin.py, line 44 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CMW0sYUCzBwNGTg0:-L63YutJ3wBAIIMxY3Ip:buw9hko) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/app/admin.py#L44)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Yeah,  I agree on making `api_add_food` and `api_edit_food` almost if not entirely identical.

I'd like it to be like:

```python
def api_add_food():
    f = _make_food_from_form()
    food.put(f)
    return flask.redirect('/%s' % f.key.string_id())
...

def api_edit_food(food_name):
    f = food.update(food_name, _make_food_from_form())
    return flask.redirect('/%s' % f.key.string_id())
```

>Unit tests that ensure that the right values get assigned to food objects?

Yeah, I'm mainly interested in verifying scenarios like:

1. Food already exists, we call `update` with the exact same Food -> Verify that everything stays the same except the updated timestamp.
1. Food already exists,we call `update` with some fields changed -> Verify that those fields changed + new update timestamp.


</blockquote></details>

Making a new Food on updates breaks the way the creation_time and last_modified_time properties currently work, that's why I pivoted away from creating a new object everytime in this PR and just handing over keys. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69)*

**Comment by mtlynch** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/admin.py, line 44 at r1](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-L62CMW0sYUCzBwNGTg0:-L63fA2lunSUyA_hxSH7:b-li1yjn) ([raw file](https://github.com/mtlynch/isitketo_webapp/blob/c76f674f03646d242ee5663c996532ad3baddc04/app/admin.py#L44)):*
<details><summary><i>Previously, fernandalavalle wrote…</i></summary><blockquote>

Making a new Food on updates breaks the way the creation_time and last_modified_time properties currently work, that's why I pivoted away from creating a new object everytime in this PR and just handing over keys. 
</blockquote></details>

Oh gotcha. Then can we do it as is, but rename `_update_food_from_form` to `_populate_food_from_form`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mtlynch/isitketo_webapp/69#-:-L63fL5GFVXJZLRAjiol:bnfp4nl)*

**Pull request merged**
